Feat/admin voting
Decide-chiquito/decide-part-chiquito pull request #64
Opened 2023-11-13 11:01 UTC by alesanfe

2023-11-13 11:26 UTC, marvicmar requested changes

2023-11-13 11:26 UTC, marvicmar commented on decide/authentication/urls.py
> +from django.contrib.auth import views as auth_views
Eliminar, es un bar smell.

2023-11-13 11:26 UTC, marvicmar commented on decide/census/views.py
> -        HTTP_400_BAD_REQUEST as ST_400,
¿No faltaría el error 400?

2023-11-15 09:58 UTC, JuanCarlosRL approved these changes
Todo bien

2023-11-15 11:03 UTC, marvicmar approved these changes
Código correcto

2023-11-15 11:05 UTC, merged